### ISSUE TITLE
Slate wont leave me alone

### ISSUE THREAD

**Issue by BeansAreNeat** [PacificEngine/OW_CommonResources#12] opened 2022-04-16 20:48 UTC
Slate tells me about the navigation system every single time i get on the elevator. I have to uninstall the mod and even reset the whole game just to get him to stop

**Comment by salomj** [comment] 2022-04-26 02:02
What other mods do you have installed? Can you provide more details?

**Comment by salomj** [comment] 2022-05-09 20:12
For context, Common Resources mod actually doesn't have any features enabled, which means it makes no changes to the game. Other mods utilizing common resources enable those features. So it would be good to know which mods, so that I know what features from common resources might be causing this issue.

**Comment by salomj** [comment] 2022-06-02 20:06
Closing issue as I cannot reproduce and no extra details were provided.

**Closed as completed by salomj** 2022-06-02 20:06 UTC
